### PR TITLE
Arrielle's additions to CNERmoG

### PR DESCRIPTION
**Pull request by opotowsky**
bitmoji

### CODE REVIEW

**Comment by opotowsky** [comment]
Let me know if my favorite emoji T-shirt is too uncouth. I'll be sad but I'll change it!

**Comment by pshriwise** [comment]
I don't think it is :laughing: 

but I think for the `Staff and Students` page we were going an "emoji" bitmoji (can search emoji in bitmoji plugin here for example). That cool?

**Comment by opotowsky** [comment]
bitmoji

**Comment by pshriwise** [comment]
Love it :smiley: Looks great, thanks @opotowsky!

**Comment by opotowsky** [comment]
Thank YOU @pshriwise!

**Pull request merged**
